#!/bin/bash
#
# Descriptor:
#	Install cuda
#
# Modify History
# --------------
# 00a 30Apr18 lzw create, split from install_caffe2

install_cuda()
{
    version_cuda()
    {
        echo "$(cat /usr/local/cuda/version.txt | cut -d ' ' -f 3 | cut -d '.' -f 1-2)"
    }
    if [[ -e /usr/local/cuda/version.txt ]]; then
        if [[ "$(version_cuda)" == "$1" ]]; then
            echo "CUDA $1 is already installed."
            return
        fi
    fi

    echo "Starting install CUDA $1"
    sudo apt-get install wget -y --no-install-recommends
    wget "http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb"
    sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
    sudo apt-get update
    sudo apt-get install -y cuda-8-0

    echo "CUDA $(version_cuda) is installed successfully!"
}

install_cudnn()
{
    version_cudnn()
    {
        cudnn_major=$(cat /usr/local/cuda/include/cudnn.h | grep "#define CUDNN_MAJOR" | cut -d ' ' -f 8)
        cudnn_minor=$(cat /usr/local/cuda/include/cudnn.h | grep "#define CUDNN_MINOR" | cut -d ' ' -f 8)
        echo "${cudnn_major}"."${cudnn_minor}"
    }

    if [[ -e /usr/local/cuda/include/cudnn.h ]]; then
        if [[ "$(version_cudnn)" == "$2" ]]; then
            echo "cuDNN $2 is already installed."
            return
        fi
        echo "Updte cuDNN from $(version_cudnn) to $2."
    fi

    echo "Starting install cuDNN $2.}"

    cudnn_file="cudnn-$1-linux-x64-v$2.tgz"
    wget "http://developer.download.nvidia.com/compute/redist/cudnn/v$1/${cudnn_file}"
    sudo tar -xzf "${cudnn_file}" -C /usr/local
    rm "${cudnn_file}" && sudo ldconfig

    echo "cuDNN $(version_cudnn) is installed successfully!"

    # Test cuDNN installation.
    # cp -r /usr/src/cudnn_samples_v7/ $HOME
    # cd  $HOME/cudnn_samples_v7/mnistCUDNN
    # make clean && make
    # ./mnistCUDNN
}
